### ISSUE TITLE
overlap_peakfi_with_bam.pl

### ISSUE THREAD

**Issue by alexmondaini** [YeoLab/merge_peaks#6]
I'm getting the following issue

```
WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
reading peak file /var/lib/cwl/stgf7e182df-5cae-4505-b70d-9330e5e663fd/10249_sample3_10249_sample4_ready.split1.peakClusters.bed
now doing expt /var/lib/cwl/stg0607570c-da94-4f28-b3f1-fd8352700c76/10249_sample3_10249_sample4_ready.split1.bam
R1 strand error 403
Use of uninitialized value $strand in concatenation (.) or string at /opt/merge_peaks/bin/perl/overlap_peakfi_with_bam.pl line 402, <B> line 107.
R1 strand error 403
```

Command is:

```
cwltool --singularity /groups/cgsd/alexandre/eclip/workflow/merge_peaks/cwl/wf_full_IDR_pipeline_2inputs_scatter.cwl /groups/cgsd/alexandre/eclip/workflow/merge_peaks/analysis.yml
```

My yaml is:
```
#!/usr/bin/env eCLIP_full_IDR_pipeline_2inputs_scatter_singleNode

species: hg19
samples:
  - 
    - name: "10249_sample1_10249_sample2_merged_clip_and_input"
      ip_bam: 
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-View/shard-0/execution/10249_sample1_10249_sample2_ready.bam
      input_bam:
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-View/shard-2/execution/10249_sample5_10249_sample6_ready.bam
      peak_clusters:
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-Clipper/shard-0/execution/10249_sample1_10249_sample2_ready.bed
    - name: "10249_sample3_10249_sample4_merged_clip_and_input"
      ip_bam: 
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-View/shard-1/execution/10249_sample3_10249_sample4_ready.bam
      input_bam:
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-View/shard-3/execution/10249_sample7_10249_sample8_ready.bam
      peak_clusters:
        class: File
        path: /groups/cgsd/alexandre/cromwell-executions/SamtoolsMerge/f355824c-d131-4077-ac49-9b5877ee7dba/call-Clipper/shard-1/execution/10249_sample3_10249_sample4_ready.bed
chrom_sizes:
  class: File
  path: /groups/cgsd/alexandre/eclip/workflow/chrom.sizes
```

And images used are:

```
brianyee_clipper:5d865bb.sif
brianyee_merge_peaks:0.1.0.sif
brianyee_samtools:1.6.sif
```
